env:
  global:
    secure:

language: node_js

matrix:
    include:
        - os: linux
          node_js:
            - "8"
            - "12"
        - os: windows
          node_js:
            - "8"
            - "12"

# https://docs.travis-ci.com/user/caching/
# disable npm caching
cache:
  npm: false

# https://github.com/codecov/example-node
install:
  - npm install
  # move to devDependencies @ package.json
  #- npm install -g nyc
  #- npm install -g codecov

script:
  - npm test

after_success:
  - npm run report-coverage
