env:
  global:
    secure:

language: node_js
node_js:
  - "8"
  - "10"
  - "12"
# https://docs.travis-ci.com/user/caching/
# disable npm caching
cache:
  npm: false

# https://github.com/codecov/example-node
install:
  - npm install
  # move to devDependencies @ package.json
  #- npm install -g nyc
  #- npm install -g codecov

script:
  - npm test

after_success:
  - npm run report-coverage
